# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

score = 0
print("WELCOME TO QUIZ")
name =str(input("what is ur name: "))
print("okay" ,name,"lets start the quiz now")
quiz1 = int(input("what is the awnser of 35 plus 16: "))
if quiz1== 51 :
  print("correct")
  score +51= 1
else:
  print("incorrect")
  score = 0
quiz2 = int(input("what is the square root of 64: "))
if quiz2== 8:
 print("correct")
 score += 1
else:
 print("incorrect")
quiz3= int(input("what is the square of 7: "))
if quiz3== 49:
 print("correct")
 score += 1
else:
 print("incorrect")
print("end of quiz calculating final score")
print("final score is:", score)
if score==1:
  print("not bad but can improve")
elif score==2:
  print("good")
else:
  print("excellent")